/**
 * First 20 elements — the set Class 10 students are expected to know cold.
 * Atomic masses are the rounded values used in NCERT problem-solving.
 * Valency = combining capacity as taught at this level.
 */

export const ELEMENTS = [
  {
    z: 1,
    symbol: "H",
    name: "Hydrogen",
    mass: 1,
    valency: 1,
    shells: "1",
    group: "nonmetal",
    note: "The lightest element — 1 electron, 1 shell, valency 1.",
  },
  {
    z: 2,
    symbol: "He",
    name: "Helium",
    mass: 4,
    valency: 0,
    shells: "2",
    group: "noble",
    note: "A noble gas — its shell is full, so it never bonds. Valency 0!",
  },
  {
    z: 3,
    symbol: "Li",
    name: "Lithium",
    mass: 7,
    valency: 1,
    shells: "2,1",
    group: "metal",
    note: "1 electron in the outer shell — gives it away easily. Valency 1.",
  },
  {
    z: 4,
    symbol: "Be",
    name: "Beryllium",
    mass: 9,
    valency: 2,
    shells: "2,2",
    group: "metal",
    note: "2 outer electrons to give away → valency 2.",
  },
  {
    z: 5,
    symbol: "B",
    name: "Boron",
    mass: 11,
    valency: 3,
    shells: "2,3",
    group: "metalloid",
    note: "3 outer electrons → valency 3.",
  },
  {
    z: 6,
    symbol: "C",
    name: "Carbon",
    mass: 12,
    valency: 4,
    shells: "2,4",
    group: "nonmetal",
    note: "4 hands to hold! The star of Chapter 4.",
  },
  {
    z: 7,
    symbol: "N",
    name: "Nitrogen",
    mass: 14,
    valency: 3,
    shells: "2,5",
    group: "nonmetal",
    note: "5 outer electrons, needs 3 more → valency 3.",
  },
  {
    z: 8,
    symbol: "O",
    name: "Oxygen",
    mass: 16,
    valency: 2,
    shells: "2,6",
    group: "nonmetal",
    note: "6 outer electrons, needs 2 more → valency 2. That's why H₂O!",
  },
  {
    z: 9,
    symbol: "F",
    name: "Fluorine",
    mass: 19,
    valency: 1,
    shells: "2,7",
    group: "nonmetal",
    note: "Needs just 1 electron → valency 1. Super reactive!",
  },
  {
    z: 10,
    symbol: "Ne",
    name: "Neon",
    mass: 20,
    valency: 0,
    shells: "2,8",
    group: "noble",
    note: "Full outer shell (8) → valency 0. Glows in signs!",
  },
  {
    z: 11,
    symbol: "Na",
    name: "Sodium",
    mass: 23,
    valency: 1,
    shells: "2,8,1",
    group: "metal",
    note: "1 spare electron → valency 1. Half of table salt!",
  },
  {
    z: 12,
    symbol: "Mg",
    name: "Magnesium",
    mass: 24,
    valency: 2,
    shells: "2,8,2",
    group: "metal",
    note: "2 spare electrons → valency 2. The dazzling ribbon!",
  },
  {
    z: 13,
    symbol: "Al",
    name: "Aluminium",
    mass: 27,
    valency: 3,
    shells: "2,8,3",
    group: "metal",
    note: "3 spare electrons → valency 3. Your kitchen foil.",
  },
  {
    z: 14,
    symbol: "Si",
    name: "Silicon",
    mass: 28,
    valency: 4,
    shells: "2,8,4",
    group: "metalloid",
    note: "4 outer electrons like carbon → valency 4. Powers computer chips.",
  },
  {
    z: 15,
    symbol: "P",
    name: "Phosphorus",
    mass: 31,
    valency: 3,
    shells: "2,8,5",
    group: "nonmetal",
    note: "5 outer electrons, needs 3 → valency 3. Used in matchsticks.",
  },
  {
    z: 16,
    symbol: "S",
    name: "Sulphur",
    mass: 32,
    valency: 2,
    shells: "2,8,6",
    group: "nonmetal",
    note: "6 outer electrons, needs 2 → valency 2. The yellow powder!",
  },
  {
    z: 17,
    symbol: "Cl",
    name: "Chlorine",
    mass: 35.5,
    valency: 1,
    shells: "2,8,7",
    group: "nonmetal",
    note: "Needs 1 electron → valency 1. Note the odd mass: 35.5!",
  },
  {
    z: 18,
    symbol: "Ar",
    name: "Argon",
    mass: 40,
    valency: 0,
    shells: "2,8,8",
    group: "noble",
    note: "Full outer shell → valency 0. Fills light bulbs.",
  },
  {
    z: 19,
    symbol: "K",
    name: "Potassium",
    mass: 39,
    valency: 1,
    shells: "2,8,8,1",
    group: "metal",
    note: "1 spare electron → valency 1. Top of the reactivity ladder!",
  },
  {
    z: 20,
    symbol: "Ca",
    name: "Calcium",
    mass: 40,
    valency: 2,
    shells: "2,8,8,2",
    group: "metal",
    note: "2 spare electrons → valency 2. Builds your bones!",
  },
];

/**
 * Mnemonic chunks — the classic Indian-classroom sentence, broken into
 * bite-sized groups so she memorises 5 at a time instead of 20 at once.
 */
export const MNEMONIC_CHUNKS = [
  {
    id: "chunk1",
    range: "Elements 1–5",
    line: "Happy Henry Lives Beside Boron",
    symbols: ["H", "He", "Li", "Be", "B"],
    words: ["Happy", "Henry", "Lives", "Beside", "Boron"],
    cues: [1, 2, 2, 2, 1],
    story:
      "Picture a cheerful boy named Henry who lives in a house right next to a big boron rock.",
  },
  {
    id: "chunk2",
    range: "Elements 6–10",
    line: "Cottage Near Our Friend Nelly",
    symbols: ["C", "N", "O", "F", "Ne"],
    words: ["Cottage", "Near", "Our", "Friend", "Nelly"],
    cues: [1, 1, 1, 1, 2],
    story:
      "Henry's cottage sits near his friend Nelly's place — she has neon lights outside!",
  },
  {
    id: "chunk3",
    range: "Elements 11–15",
    line: "Naughty Magpies Always Sing Perfectly",
    symbols: ["Na", "Mg", "Al", "Si", "P"],
    words: ["Naughty", "Magpies", "Always", "Sing", "Perfectly"],
    cues: [2, 2, 2, 2, 1],
    story:
      "In Nelly's garden, some cheeky magpies sit on the fence singing in perfect tune. (Careful — Ma-gpies is written Mg!)",
  },
  {
    id: "chunk4",
    range: "Elements 16–20",
    line: "Some Clever Argument Killed Cats",
    symbols: ["S", "Cl", "Ar", "K", "Ca"],
    words: ["Some", "Clever", "Argument", "Killed", "Cats"],
    cues: [1, 2, 2, 1, 2],
    story:
      "The magpies got into a clever argument that scared all the neighbourhood cats away.",
  },
];

export const FULL_MNEMONIC =
  "Happy Henry Lives Beside Boron Cottage Near Our Friend Nelly, Naughty Magpies Always Sing Perfectly Some Clever Argument Killed Cats.";
